### ISSUE TITLE
License file?

### ISSUE THREAD

**Issue by SimonBiggs** [matthewwilson/SaintfieldBaptistChurch#4]
Hi @matthewwilson,

I have been charged with building our church website. I was hoping to be able to use yours as a starting place. Would that be okay with you?

Are you able to put a license file on the page?

Thanks :)

**Comment by matthewwilson** [comment]
Hi @SimonBiggs 

Yes no problem, I’ve added the Apache license.

Thanks
Matthew

**Comment by SimonBiggs** [comment]
Thanks @matthewwilson!

Much appreciated :)

**Comment by SimonBiggs** [comment]
I'm very impressed by the way. Thank you :). Let me know if you'd like any help for me to say thank you.

I'm going to be integrating my version of this with Netlify, Gatsby, and Contentful. I can let you know once it's live if you like?

Cheers,
Simon

**Comment by matthewwilson** [comment]
No problem at all. Yes let me know when it's public and I'll check it out!
